services:
  dev:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - "5173:5173"
      - "4173:4173"
    stdin_open: true
    tty: true
    restart: unless-stopped
